name: calculator
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  math_expressions: ^2.3.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  ios: true
  android: true
  image: assets/splash.png
  color: "#ffffff"
  android_12:
    image: assets/splash.png
    color: "#ffffff"